### ISSUE TITLE
Erro ao acessar disponibilidade do profissional

### ISSUE THREAD

**Issue by jplpereira** [fga-eps-mds/2020.1-eSaudeUnB-FrontEnd#29]
**Descreva o erro**
O usuário paciente não consegue acessar a disponibilidade do profissional de saúde.

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Login na plataforma;
2. Acessar lista de profissionais;
3. Clicar no botão "Agendar atendimento" de um dos profissionais.

**Comportamento esperado**
Espera-se que a disponibilidade do profissional seja apresentada.

**Captura de tela**
![image](https://user-images.githubusercontent.com/13935419/100488532-8b74c480-30ed-11eb-82f1-f32db88fe902.png)

**Comment by abner423** [comment]
JP, acredito que essa página de agendar atendimento que está dando esse erro era aquela provisória que estava pra ser substituida, que era solução provisória. No momento a consulta está sendo agendada pelo calendario. Devemos no caso retirar o history.push dessa página provisória e fazer o envio para a página de calendário

**Comment by luisgfmarques** [comment]
acabei de realizar o teste, aparentemente ja foi corrigido na develop
