### ISSUE TITLE
Bugs nos estilos

### ISSUE THREAD

**Issue by Rafaelltm** [fga-eps-mds/2020.1-eSaudeUnB-FrontEnd#39]
**Describe the bug**
1- na tela de perfil de usuário, uma das 3 partes do perfil a serem preenchidas está ficando encima do footer.
2- na tela de listagem de profissionais de administrador, quando são criados mais de 3 profissionais o estilo quebra.
3- o modal de alterar senha na tela de perfil de psicólogo não está estilizado como no perfil de usuário.

**To Reproduce**
Bug 1 - {
1. Faça login como um usuário.
2. Clique na seta da direita do formulário a ser preenchido.
}

Bug 2 - {
1. Faça login como administrador.
2. Crie 4 ou mais profissionais.
}

Bug 3 - {
1. Faça login como Profissional.
2. Clique em "Alterar Senha"
}

**Expected behavior**
1- As três partes do formúlario a ser preenchido no perfil devem respeitar o limite do footer e da navbar na tela.
2- Mesmo com vários profissionais cadastrados na plataforma, a tela do administrador deve manter o estilo original.
3- Os dois modais de alterar senha devem estar estilizados da mesma maneira, seguindo os padrões da aplicação.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [CPU]
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [87.0.4280.88]

**Additional context**
1- 
![erro_psy_profile(1-3)](https://user-images.githubusercontent.com/54643266/101991428-5343b900-3c8b-11eb-9738-118181d4a531.png)
![erro_psy_profile(2-3)](https://user-images.githubusercontent.com/54643266/101991429-5474e600-3c8b-11eb-9a3b-6b10a1a53e19.png)
![erro_psy_profile(3-3)](https://user-images.githubusercontent.com/54643266/101991432-563ea980-3c8b-11eb-85d4-8d69f590ab20.png)

2-
![erro_admin_psy_list(1-2)](https://user-images.githubusercontent.com/54643266/101991424-52128c00-3c8b-11eb-99a4-a60fae1317c4.png)
![erro_admin_psy_list(2-2)](https://user-images.githubusercontent.com/54643266/101991426-5343b900-3c8b-11eb-81e8-87fb45966377.png)

**Comment by linktocaio** [comment]
@pedroholiveira1998 e eu ja resolvemos esse problema na tela de listagem de profissionais de administrador. Esta nesse PR: [Fix/designer fixes #38](https://github.com/fga-eps-mds/2020.1-eSaudeUnB-FrontEnd/pull/38)

**Comment by linktocaio** [comment]
@pedroholiveira1998 também arrumou o bug 3: "O modal de alterar senha na tela de perfil de psicólogo não está estilizado como no perfil de usuário."

**Comment by linktocaio** [comment]
bug 1 corrigido, footer não esta mais ficando por cima do content
